const creatures = [
    { name: "custom", ac: 0, hp: 0 },
    { name: "annis-hag", ac: 17, hp: 75 },
    { name: "apprentice-wizard", ac: 10, hp: 9 },
    { name: "archmage", ac: 12, hp: 99 },
    { name: "assassin", ac: 15, hp: 78 },
    { name: "barbed-devil", ac: 15, hp: 110 },
    { name: "crocodile", ac: 13, hp: 85 },
    { name: "death-dog", ac: 12, hp: 39 },
    { name: "displacer-beast", ac: 15, hp: 7 },
    { name: "fire-elemental", ac: 13, hp: 102 },
    { name: "giant-constrictor-snake", ac: 12, hp: 60 },
    { name: "giant-spider", ac: 14, hp: 26 },
    { name: "goblin", ac: 15, hp: 7 },
    { name: "hell-hound", ac: 15, hp: 45 },
    { name: "hobgoblin", ac: 18, hp: 11 },
    { name: "hobgoblin-captain", ac: 17, hp: 39 },
    { name: "hobgoblin-warlord", ac: 20, hp: 97 },
    { name: "imp", ac: 13, hp: 10 },
    { name: "incubus", ac: 15, hp: 66 },
    { name: "knight", ac: 18, hp: 52 },
    { name: "kobold", ac: 12, hp: 5 },
    { name: "mage", ac: 12, hp: 40 },
    { name: "minotaur", ac: 14, hp: 76 },
    { name: "nightmare", ac: 13, hp: 68 },
    { name: "ogre", ac: 11, hp: 59 },
    { name: "ogre-zombie", ac: 8, hp: 85 },
    { name: "orc", ac: 13, hp: 15 },
    { name: "orc-war-chief", ac: 16, hp: 93 },
    { name: "phase-spider", ac: 13, hp: 32 },
    { name: "priest", ac: 13, hp: 27 },
    { name: "quasit", ac: 13, hp: 7 },
    { name: "quickling", ac: 16, hp: 10 },
    { name: "salamander", ac: 15, hp: 90 },
    { name: "scout", ac: 13, hp: 16 },
    { name: "shadow-demon", ac: 13, hp: 66 },
    { name: "spined-devil", ac: 13, hp: 22 },
    { name: "succubus", ac: 15, hp: 66 },
    { name: "swarm-of-poisonous-snakes", ac: 14, hp: 36 },
    { name: "troll", ac: 15, hp: 84 },
    { name: "vampire-spawn", ac: 15, hp: 82 },
    { name: "wight", ac: 14, hp: 45 },
    { name: "young-red-dragon", ac: 18, hp: 178 },
];

export default creatures;
